obj=jigsaw.o PicturePuzzle.o PictureElement.o PictureElementSet.o
src=jigsaw.cpp PicturePuzzle.cpp PictureElement.cpp PictureElementSet.cpp

jigsaw:$(obj)
	g++ -o jigsaw $(obj)
clean:
	rm -fr *.o jigsaw
